
jakarta.persistence.jdbc.url=${DB_URL}
jakarta.persistence.jdbc.user=${DB_USERNAME}
jakarta.persistence.jdbc.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
