spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

customer.service.base-url=https://customer-service-production-9673.up.railway.app